# Generated by Django 6.0 on 2026-02-07 20:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('biker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='deliveries.biker')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='deliveries.delivery')),
            ],
            options={
                'db_table': 'delivery_locations',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
