# Generated by Django 6.0 on 2026-02-15 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_deliverylocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverylocation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='deliverylog',
            options={},
        ),
        migrations.RemoveField(
            model_name='biker',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='biker',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deliverylog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='biker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biker',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DELIVERY', 'On Delivery')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dropoff_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='biker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.biker'),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='biker',
            table=None,
        ),
        migrations.AlterModelTable(
            name='delivery',
            table=None,
        ),
        migrations.AlterModelTable(
            name='deliveryassignment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='deliverylocation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='deliverylog',
            table=None,
        ),
    ]
