# Generated by Django 6.0 on 2026-02-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_deliverylocation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverylocation',
            old_name='latitude',
            new_name='pickup_latitude',
        ),
        migrations.RenameField(
            model_name='deliverylocation',
            old_name='longitude',
            new_name='pickup_longitude',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SEARCHING', 'Searching'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
