# Generated by Django 6.0.1 on 2026-02-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_rename_latitude_deliverylocation_pickup_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverylocation',
            old_name='pickup_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='deliverylocation',
            old_name='pickup_longitude',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='biker',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biker',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
